### ISSUE TITLE
Poor performance on Digital Ocean droplet

### ISSUE THREAD

**Issue by MMquant** [blechschmidt/massdns#82] opened 2020-09-11 07:50 UTC
_Massdns_ used to work perfectly for at least 1 year on Digital Ocean Droplets (DOD) with performance ~22k pps.
Recently after I `apt update && apt upgrade` my Ubuntu machine on DOD the _massdns_ became unusable with performance ~50-300 pps.
Now _massdns_ often completely freezes SSH connection so hard reset via DOD cPanel is needed. It has never happened before.

Currently I'm using _massdns_ from my home connection (150Mb/s) with the same public resolvers which I used at DOD and I'm getting ~8-10k pps. I tried to create fresh DOD and clean install _massdns_ but it didn't help.
I even opened support ticket a explained the problem to the DO support but got response that all networking regarding my DOD is fully functional.

Does anyone have similar issues on latest Ubuntu machines or/and DODs?

**Comment by mzpqnxow** [comment] 2020-09-19 19:11
I would recommend experimenting with different hashmap size, socket count and interval settings. It seems very unusual to me, I don’t have any suggestions aside from those

**Comment by 00xfd** [comment] 2020-10-09 00:06
@MMquant could you solve the problem? I have the same experience and I didn't find a solution to that

**Comment by blechschmidt** [comment] 2020-10-10 20:50
I cannot reproduce this. On a $5/month Ubuntu droplet in Frankfurt I obtain a success rate of ~3k packets per second with the resolvers from https://public-dns.info/nameservers.txt as downloaded by the `get-resolvers.sh` script when resolving the Majestic million with the default parameters.

**Comment by blechschmidt** [comment] 2022-12-10 20:17
I can perform ~30k lookups per second against authoritative name servers on the cheapest DO droplet (`sed -e 's/.*/\0.facebook.com/' subdomains.txt | ./bin/massdns -r <(./scripts/auth-addrs.sh facebook.com) -o J > /dev/null`). Thus, I assume this to be a rate limiting issue with the resolvers you are using. Therefore, I am closing this issue. In the future, the goal is to add an option having MassDNS perform recursion on its own instead of having to rely on third-party resolvers.

**Closed by blechschmidt** 2022-12-10 20:17 UTC
